import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-orange-200"
      >
        <nav className="mt-7 w-full"> 
    <ul className="flex w-full">
      <Link href='/'><li className="flex items-center justify-center absolute left-32 top-7 w-14 h-14 rounded-full bg-[#D37157] text-white font-semibold">Home</li></Link>
      <li className="flex mx-auto space-x-9 bg-gradient-to-r from-rose-100 to-rose-200 shadow-lg rounded-3xl px-8 py-4 justify-around items-center w-96"><Link href='/contact'><p>Contact</p></Link>
      <Link href='/my-works/design'>
      <p>My Works</p></Link></li>
    </ul>
   </nav>        
   {children}
   <section>
    <h4>Connect with me</h4>
    <p>
    You can connect with me on various
    social media platforms
    </p>
    <div>
       <Image 
                 src="/images/twitter.png" 
                 alt="design 6" 
                 width={20} 
                 height={15} 
               />

      <Image 
                src="/images/benhance.png" 
                alt="design 6" 
                width={20} 
                height={15} 
              />
      <Image 
                src="/images/linkedin.png" 
                alt="design 6" 
                width={20} 
                height={15} 
              />
    </div>
    <div>
    <p>Back to the top</p>
     <Image 
               src="/images/arrow-up.png" 
               alt="design 6" 
               width={20} 
               height={15} 
             />
    </div>
    
   </section>
      </body>
    </html>
  );
}
